from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from slowapi.errors import RateLimitExceeded
from slowapi import _rate_limit_exceeded_handler

from app.core.config import settings
from app.core.limiter import limiter
from app.api import (
    auth_router,
    users_router,
    assessments_router,
    model_router,
    analytics_router,
    admin_router,
    otp_router,
)

app = FastAPI(
    title="Hodgkin Lymphoma Risk Prediction & Health Analytics Platform",
    description=(
        "Educational/research platform. This system does NOT provide a medical "
        "diagnosis. All predictions are model-estimated probabilities only."
    ),
    version=settings.MODEL_VERSION,
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE"],
    allow_headers=["Authorization", "Content-Type"],
)


@app.exception_handler(Exception)
async def generic_exception_handler(request: Request, exc: Exception):
    print(f"Unhandled error on {request.method} {request.url.path}: {exc}")
    return JSONResponse(
        status_code=500,
        content={"detail": "An unexpected error occurred. Please try again later."},
    )


app.include_router(auth_router.router, prefix=settings.API_PREFIX)
app.include_router(users_router.router, prefix=settings.API_PREFIX)
app.include_router(assessments_router.router, prefix=settings.API_PREFIX)
app.include_router(model_router.router, prefix=settings.API_PREFIX)
app.include_router(analytics_router.router, prefix=settings.API_PREFIX)
app.include_router(admin_router.router, prefix=settings.API_PREFIX)
app.include_router(otp_router.router, prefix=settings.API_PREFIX)


@app.get("/api/health", tags=["system"])
def health_check():
    return {
        "status": "ok",
        "environment": settings.ENVIRONMENT,
        "model_version": settings.MODEL_VERSION,
    }


@app.get("/", tags=["system"])
def root():
    return {
        "message": "Hodgkin Lymphoma Risk Prediction API",
        "docs": "/docs",
        "disclaimer": (
            "This platform is an educational/research tool and does not provide a "
            "medical diagnosis. Predictions are generated by a machine-learning "
            "model based on the information provided and should not be used as a "
            "substitute for professional medical advice or diagnostic testing."
        ),
    }