"""create initial tables

Revision ID: 462c03cb2b37
Revises: 
Create Date: 2026-08-09 17:14:09.088183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462c03cb2b37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='genderenum'), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_percentage', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_assessment_id'), 'predictions', ['assessment_id'], unique=True)
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('swollen_lymph_nodes', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('fever', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('night_sweats', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('weight_loss', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('fatigue', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('itching', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('shortness_of_breath', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('chest_discomfort', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('cough', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('abdominal_symptoms', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.Column('loss_of_appetite', sa.Enum('NOT_PRESENT', 'MILD', 'MODERATE', 'SEVERE', name='severityenum'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptoms_assessment_id'), 'symptoms', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptoms_assessment_id'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_predictions_assessment_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
